name: Build Windows Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 升级到最新版本 v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows application
        run: flutter build windows

      - name: List files
        run: dir build/windows/runner/Release

      - name: Archive the Build
        uses: actions/upload-artifact@v3  # 使用最新版本 v3
        with:
          name: windows-build
          path: build/windows/runner/Release
